#!/usr/bin/env python3
"""
predict.py -- the fixed submission interface. DO NOT EDIT THIS FILE.

`validate_submission.py` checks its SHA-256, and so does the instructor's
scorer. If you change one byte your submission will not be scored. Everything
you want to vary lives in `manifest.json` instead.

The instructor runs, on molecules you have never seen:

    python predict.py --smiles-csv test_hidden_smiles.csv \
                      --submission-dir . \
                      --out predictions.csv

Output columns: acid_id, smiles, then every target in `manifest["targets"]`
order, then the same names with `_sigma` appended.

sigma is your predictive standard deviation. It is HALF THE SCORE -- a
submission that emits a constant sigma will be accurate and badly calibrated,
and will lose to a slightly less accurate model that knows what it does not
know.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def _dataloader(smiles, batch_size=256):
    from chemprop import data, featurizers

    dps = [data.MoleculeDatapoint.from_smi(s) for s in smiles]
    dset = data.MoleculeDataset(dps, featurizers.SimpleMoleculeMolGraphFeaturizer())
    return data.build_dataloader(dset, batch_size=batch_size, shuffle=False)


def _enable_dropout(model) -> None:
    import torch.nn as tnn

    for mod in model.modules():
        if isinstance(mod, tnn.Dropout):
            mod.train()


def predict(smiles, manifest: dict, submission_dir: Path, batch_size: int = 256):
    """Return (mean (n, T), sigma (n, T)) exactly as al_toolkit does."""
    import torch
    from lightning import pytorch as pl

    from chemprop.models import load_model

    head = manifest.get("head", "regression")
    mc = int(manifest.get("mc_dropout_samples", 0) or 0)
    accelerator = manifest.get("accelerator", "auto")

    model_files = [submission_dir / "models" / f for f in manifest["model_files"]]
    missing = [p for p in model_files if not p.exists()]
    if missing:
        raise FileNotFoundError(f"missing checkpoint(s): {[p.name for p in missing]}")

    loader = _dataloader(smiles, batch_size)
    trainer = pl.Trainer(logger=False, enable_progress_bar=False,
                         enable_checkpointing=False, accelerator=accelerator,
                         devices=1)

    means, avars = [], []
    evid = None
    for p in model_files:
        model = load_model(p, multicomponent=False)
        model.eval()
        reps = mc if mc else 1
        if mc:
            _enable_dropout(model)
        for _ in range(reps):
            with torch.inference_mode():
                out = torch.concat(trainer.predict(model, loader), 0)
            out = out.float().cpu().numpy()
            if out.ndim == 3 and head == "mve":
                means.append(out[..., 0])
                avars.append(out[..., 1])
            elif out.ndim == 3 and head == "evidential":
                mu, v, alpha, beta = (out[..., 0], out[..., 1],
                                      out[..., 2], out[..., 3])
                means.append(mu)
                avars.append(beta / np.maximum(alpha - 1.0, 1e-6))
                evid = (v, alpha, beta)
            else:
                means.append(out.reshape(out.shape[0], -1))

    M = np.stack(means)
    mean = M.mean(axis=0)
    epistemic = M.var(axis=0, ddof=0) if M.shape[0] > 1 else np.zeros_like(mean)
    aleatoric = np.stack(avars).mean(axis=0) if avars else np.zeros_like(mean)
    if head == "evidential" and M.shape[0] == 1 and evid is not None:
        v, alpha, beta = evid
        epistemic = beta / np.maximum(v * (alpha - 1.0), 1e-6)
    sigma = np.sqrt(np.maximum(epistemic + aleatoric, 0.0))
    return mean, sigma


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--smiles-csv", required=True,
                    help="csv with a `smiles` column and optionally `acid_id`")
    ap.add_argument("--submission-dir", default=".")
    ap.add_argument("--out", default="predictions.csv")
    ap.add_argument("--batch-size", type=int, default=256)
    args = ap.parse_args()

    import pandas as pd

    sub = Path(args.submission_dir)
    manifest = json.loads((sub / "manifest.json").read_text())
    targets = manifest["targets"]

    df = pd.read_csv(args.smiles_csv)
    if "smiles" not in df.columns:
        raise SystemExit(f"{args.smiles_csv} has no `smiles` column")
    smiles = df["smiles"].tolist()

    mean, sigma = predict(smiles, manifest, sub, batch_size=args.batch_size)

    if mean.shape[1] != len(targets):
        raise SystemExit(
            f"model emits {mean.shape[1]} outputs but manifest lists "
            f"{len(targets)} targets -- these must match"
        )

    out = pd.DataFrame({"acid_id": df.get("acid_id", pd.Series(range(len(df)))),
                        "smiles": smiles})
    for j, t in enumerate(targets):
        out[t] = mean[:, j]
    for j, t in enumerate(targets):
        out[t + "_sigma"] = sigma[:, j]
    out.to_csv(args.out, index=False)
    print(f"wrote {args.out}  ({len(out)} rows x {len(targets)} targets)")


if __name__ == "__main__":
    main()
